/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package chapter01

class FizzBuzz {
    companion object {
        fun fizzBuzz(num: Int): String {
            return when {
                num % 15 == 0 -> "FizzBuzz"
                num % 3 == 0 -> "Fizz"
                num % 5 == 0 -> "Buzz"
                else -> num.toString()
            }
        }
    }
}

fun main() {
    for (i in 1..100) {
        println(FizzBuzz.fizzBuzz(i))
    }
}
